### ISSUE TITLE
Resolution for raytracer

### ISSUE THREAD

**Issue by pablogsal** [agarciamontoro/TFG#8]
Now the resolution variable for the raytracer Kernel is hardcoded to -1. This **needs** to be a parameter that will be provided by the caller because for example, when calling multiple times to the Kernel (as in the new unittest) we need to control the maximum step in each call. 

NOTE: For the unittest to pass (the one that compares the Mathematica integration) resolution must be `resolution = -.1`.

**Comment by pablogsal** [comment]
NOTICE that ef9cac94d8784c379f2ce38a643728309e73ca15 hardcodes the `resolution = -0.1` to make the raytracer compatible with the unittest.

Have this into account when measuring execution time.

**Comment by agarciamontoro** [comment]
Solved in 2d19bdd50616587d1f0df046b202dff458cc2755. From now on, `resolution` does not even exist: the detection of the collision is made continuously inside the solver.
